apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'robherley13@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    dns01:
        providers:
            - name: gcloud-dns
              clouddns:
                  project: senior-design-215919
                  serviceAccountSecretRef:
                      name: clouddns-key
                      key: service-account.json
