apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: wild-tyr-tools
 namespace: default
spec:
 secretName: wild-tyr-tools
 issuerRef:
   name: letsencrypt-prod-dns
   kind: ClusterIssuer
 dnsNames:
   - '*.tyr.tools'
 acme:
   config:
     - dns01:
         provider: gcloud-dns
       domains:
         - '*.tyr.tools'
