apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gcp-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "tyr-static-ip"
spec:
  backend:
    serviceName: web
    servicePort: 8080
