apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: tyr.tools
      http:
        paths:
          - path: /
            backend:
              serviceName: landing-page-svc
              servicePort: 80
    - host: court-herald.tyr.tools
      http:
        paths:
          - path: /
            backend:
              serviceName: court-herald-svc
              servicePort: 4444
    - host: app.tyr.tools
      http:
        paths:
          - path: /
            backend:
              serviceName: plague-doctor-svc
              servicePort: 5555
    - host: traefik.tyr.tools
      http:
        paths:
          - path: /
            backend:
              serviceName: traefik-web-ui
              servicePort: 80
    # - host: 'jenkins.tyr.tools'
    #     http:
    #        paths:
    #           - path: /
    #             backend:
    #                serviceName: jenkins-ci
    #                servicePort: 8080
    # - host: '*.tyr.tools'
    #   http:
    #       paths:
    #         - path: /
    #           backend:
    #               serviceName: web
    #               servicePort: 8080
