apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: tyr.tools
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend-svc
              servicePort: 1337
    # - host: 'jenkins.tyr.tools'
    #     http:
    #        paths:
    #           - path: /
    #             backend:
    #                serviceName: jenkins-ci
    #                servicePort: 8080
    # - host: '*.tyr.tools'
    #   http:
    #       paths:
    #         - path: /
    #           backend:
    #               serviceName: web
    #               servicePort: 8080
