apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-data
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  local:
    path: /home/rherley/k8s_pvc/data/traefik
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-local-claim
  namespace: kube-system
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi