apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: 'mongo'
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: 'app'
                    operator: In
                    values:
                      - mongo
              topologyKey: 'kubernetes.io/hostname'
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: mongo-local-claim
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 3Gi
