apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  local:
    path: /home/rherley/k8s_pvc/data/db
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub2